#!/bin/bash

main() {
	# Regex to validate the type pattern
	REGEX="\A((?:Merge[ a-z-]* branch.*)|(?:Revert*)|(?:(?:build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(?:\(.*\))?!?: .*))((?:\n\n)(?:[^-:#]+\n{0,2})+)?(\n\n(?:(?:[A-z-]|(?:BREAKING CHANGE)|(?:BREAKING-CHANGE))+: [A-z #1-9.]+\n?){0,})?\Z"

	FILE=`cat $1` # File containing the commit message

	echo "Commit Message: ${FILE}"

	if ! perl -0777 -ne "exit 1 unless /$REGEX/g" <<< "$FILE"; then
		echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard.​"
		exit 1
	else
		echo >&2 "Valid commit message."
	fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main $1
fi
